// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VibeMock.Data;

#nullable disable

namespace VibeMock.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VibeMock.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tech-related content",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lifestyle and wellness",
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Music and entertainment",
                            Name = "Music"
                        });
                });

            modelBuilder.Entity("VibeMock.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Admin",
                            CategoryId = 1,
                            Content = "Experience the future of modern web applications with stunning design and powerful features.",
                            CreatedDate = new DateTime(2026, 1, 29, 1, 38, 55, 572, DateTimeKind.Local).AddTicks(7706),
                            ImageUrl = "/images/hero-bg.jpg",
                            Title = "Welcome to Vibe"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Admin",
                            CategoryId = 2,
                            Content = "Clean, responsive layouts that work beautifully on all devices.",
                            CreatedDate = new DateTime(2026, 1, 29, 1, 38, 55, 572, DateTimeKind.Local).AddTicks(7709),
                            ImageUrl = "/images/design.jpg",
                            Title = "Modern Design"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Admin",
                            CategoryId = 1,
                            Content = "Built with .NET Core and Entity Framework for robust performance.",
                            CreatedDate = new DateTime(2026, 1, 29, 1, 38, 55, 572, DateTimeKind.Local).AddTicks(7711),
                            ImageUrl = "/images/features.jpg",
                            Title = "Powerful Features"
                        });
                });

            modelBuilder.Entity("VibeMock.Models.Post", b =>
                {
                    b.HasOne("VibeMock.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VibeMock.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
